language: d

install:
  - DMD_VER=2.066.1
  - DUB_VER=0.9.22
  - curl -fsSL http://downloads.dlang.org/releases/2014/dmd.${DMD_VER}.linux.zip > dmd.zip
  - unzip -q -d ~ dmd.zip
  - curl -fsSL http://code.dlang.org/files/dub-${DUB_VER}-linux-x86_64.tar.gz | tar -C ~/dmd2/linux/bin64 -xzf -
  - export PATH="${HOME}/dmd2/linux/bin64:${PATH}"
  - export LD_LIBRARY_PATH="${HOME}/dmd2/linux/lib64:${LD_LIBRARY_PATH}"

  - LIBGIT2_VER=0.20.0
  - curl -fsSL https://github.com/libgit2/libgit2/archive/v${LIBGIT2_VER}.tar.gz | tar -xzf -
  - pushd libgit2-${LIBGIT2_VER}/
  - cmake -DCMAKE_INSTALL_PREFIX=${HOME}/libgit2 .
  - make -j2
  - make install
  - popd
  - export LIBRARY_PATH="${HOME}/libgit2/lib:${LIBRARY_PATH}"
  - export LD_LIBRARY_PATH="${HOME}/libgit2/lib:${LD_LIBRARY_PATH}"

script:
  - dub test
